### PR TITLE
Update to check for "Linux" Platform as oppose to Linux on Azure. 

### PR DESCRIPTION
**Pull request by brunbimmer**
Added another method to verify a Linux environment. Tested and runs on a Kubernetes/Docker environment.

### CODE REVIEW

**Comment by brunbimmer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by brunbimmer** [comment]
recheck

**Comment by brunbimmer** [comment]
@stesee Are you able to approve? I would like to get this into my next build as a Nuget library which will be happening later today.

**Comment by stesee** [comment]
> @stesee Are you able to approve? I would like to get this into my next build as a Nuget library which will be happening later today.

Your current proposal opens security issues that won't be merged. Let's try to be more specific on creation of the exceptions to sandboxing or use the linked ctor overload, where you can inject the parameter for no-sandbox.

**Comment by brunbimmer** [comment]
> > @stesee Are you able to approve? I would like to get this into my next build as a Nuget library which will be happening later today.
> 
> Your current proposal opens security issues that won't be merged. Let's try to be more specific on creation of the exceptions to sandboxing or use the linked ctor overload, where you can inject the parameter for no-sandbox.

I need the "headless" set to "true" when passing in the "--no-sandbox" parameter. Can I ask how the proposal opens security issues?

**Comment by brunbimmer** [comment]
@stesee Just noticed I can pass in the "LaunchOptions" as a second parameter in the CreateAsync method which negates the value behind my Pull Request.

**Pull request closed without merging**
